language: php

php:
  - 5.4
  - 5.5
  - 5.6
  
before_install:
  - pecl install pthreads-2.0.10
  - pecl install xdebug
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
