language: php

php:
  - 5.4
  - 5.5
  - 5.6
  
before_install:
  - wget https://github.com/appserver-io-php/pthreads/archive/v2.0.10.tar.gz
  - tar -xvzf v2.0.10.tar.gz
  - cd pthreads-2.0.10
  - phpize
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf pthreads-2.0.10
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

before_script:
  - phpenv config-add travis-php.ini
  - composer selfupdate

script:
  - ant composer-init
  - ant build

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
