language: php

php:
  - 5.4
  - 5.5
  - 5.6
  
before_install:
  - pecl install xdebug
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - wget https://github.com/appserver-io-php/pthreads/archive/v1.0.6.tar.gz
  - tar -xvzf v1.0.6.tar.gz
  - cd pthreads-1.0.6
  - phpize
  - ./configure
  - make
  - make install
  - cd ..

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
